
title: Eu
url: 'http://leandromundim.com'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Leandro Mundim
tagline: Empres√°rio
pic: avatar.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mundim@icmc.usp.br
phone: +55 (16)99616 4132
website: leandromundim.com/blog #do not add http://
linkedin: leandromundim
github: leandromundim
twitter: '@drmundim'

#Update all the sections by editing the files inside _includes folder.
